### ISSUE TITLE
数据集相关

### ISSUE THREAD

**Issue by ghost** [JasonJerome/Pointer-meter-reading-algorithm-by-Python#1]
想问下可以求一下大佬训练用的数据集吗，小弟目前被老师安排了这个方向但是找不到合适的数据集，希望大佬可以指点迷津

**Comment by JasonJerome** [comment]
不好意思嗷，我这边的数据集大多是和企业合作的，不方便分享哦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JasonJerome/Pointer-meter-reading-algorithm-by-Python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 中午11:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[JasonJerome/Pointer-meter-reading-algorithm-by-Python] 数据集相关 (Issue #1)





 
想问下可以求一下大佬训练用的数据集吗，小弟目前被老师安排了这个方向但是找不到合适的数据集，希望大佬可以指点迷津
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
